# Generated by Django 6.0 on 2025-12-11 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('business_hours', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('amenities', models.TextField(blank=True, default=None, null=True)),
                ('gst_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fssai_license', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
