# Generated by Django 6.0 on 2025-12-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='hostel',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
