# Generated by Django 6.0 on 2025-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_city_hostel_contact_phone_hostel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='food_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(blank=True, choices=[('pg', 'PG'), ('hostel', 'Hostel'), ('hotel', 'Hotel')], max_length=20),
        ),
        migrations.AddField(
            model_name='hostel',
            name='owner_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_proof/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='police_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='police_verification_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='property_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_proof/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/trade_license/'),
        ),
    ]
