# Generated by Django 6.0 on 2025-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostel_food_provided_hostel_hostel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='owner_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/id_proof/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='property_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/property_proof/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/trade_license/'),
        ),
    ]
