# Generated by Django 6.0 on 2025-12-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_hostel_contact_email_alter_hostel_owner_id_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('sharing_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], default='single', max_length=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_water_heater', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='hostels.hostel')),
            ],
            options={
                'ordering': ['floor', 'room_code'],
                'unique_together': {('hostel', 'room_code')},
            },
        ),
    ]
