# Generated by Django 6.0 on 2025-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=15),
        ),
    ]
