# Generated by Django 6.0 on 2025-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_room_is_maintenance_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='category',
            field=models.CharField(choices=[('mens', "Men's"), ('womens', "Women's"), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_double',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rent for double sharing', max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_single',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rent for single sharing', max_digits=10),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_triple',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rent for triple sharing', max_digits=10),
        ),
    ]
