# Generated by Django 6.0 on 2025-12-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_hostel_category_hostel_price_double_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='category',
            field=models.CharField(blank=True, choices=[('mens', "Men's"), ('womens', "Women's"), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
    ]
