# Generated by Django 5.2.8 on 2025-12-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_address_users_city_users_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
    ]
